# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

# pylint: disable=missing-module-docstring
import pytest


def pytest_addoption(parser: pytest.Parser):
    """Parse additional pytest options.

    Args:
        parser: pytest command line parser.
    """
    # --openstack-rc points to an openstack credential file in the "rc" file style
    # Here's an example of that file
    # $ echo ~/openrc
    # export OS_REGION_NAME=RegionOne
    # export OS_PROJECT_DOMAIN_ID=default
    # export OS_AUTH_URL=http://10.0.0.1/identity
    # export OS_TENANT_NAME=demo
    # export OS_USER_DOMAIN_ID=default
    # export OS_USERNAME=demo
    # export OS_VOLUME_API_VERSION=3
    # export OS_AUTH_TYPE=password
    # export OS_PROJECT_NAME=demo
    # export OS_PASSWORD=nomoresecret
    # export OS_IDENTITY_API_VERSION=3
    parser.addoption("--openstack-rc", action="store", default="")
    # Akismet API key for testing the Akismet plugin
    parser.addoption("--akismet-api-key", action="store", default="")
    # OpenID username and password for testing the OpenID plugin
    parser.addoption("--openid-username", action="store", default="")
    parser.addoption("--openid-password", action="store", default="")
    # Launchpad team for the launchpad OpenID account
    parser.addoption("--launchpad-team", action="store", default="")
    # Kubernetes cluster configuration file
    parser.addoption("--kube-config", action="store", default="")
    # Config WordPress with a mysql database deployed as a pod in kubernetes instead of mysql charm
    parser.addoption("--test-db-from-config", action="store_true", default=False)
    # Number of WordPress units should the test deploy
    parser.addoption("--num-units", action="store", type=int, default=1)
    # A directory to store screenshots generated by test_upgrade
    parser.addoption("--screenshot-dir", action="store", default="")
    # WordPress docker image built for the WordPress charm.
    parser.addoption("--wordpress-image", action="store", default="localhost:32000/wordpress:test")
