{
 "title": "Wordpress Operator Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Wordpress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Wordpress Operator",
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "options": {
    "content": "# Wordpress Operator for Juju\n\n- Github [URL](https://github.com/canonical/wordpress-k8s-operator)\n\n- For more information, visit wordpress [charmhub](https://charmhub.io/wordpress-k8s)\n\n"
   }
  },
  { "title": "Apache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Uptime total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apache_uptime_seconds_total{juju_application=\"$juju_application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apache version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apache_version{juju_application=\"$juju_application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apache Workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apache_workers{juju_application=\"$juju_application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apache load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "apache_load{juju_application=\"$juju_application\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}