# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

from typing import Any, Dict, List, NamedTuple, Optional, Tuple, TypedDict, Union

import ops
import ops.framework
import ops.model
import opslib.mysql
from charms.nginx_ingress_integrator.v0.ingress import IngressRequires

from types_ import CommandExecResult, DatabaseConfig, ExecResult

class AddonInfoDict(TypedDict):
    name: str
    status: str
    update: str
    version: str

# FIXME: fixme after generic named tuple is fully supported
class ExecResultListOfAddonInfoDict(NamedTuple):
    success: bool
    result: Optional[List[AddonInfoDict]]
    message: str

class WordpressCharm(ops.charm.CharmBase):
    class _ReplicaRelationNotReady(Exception): ...

    class _ExecResult(NamedTuple):
        success: bool
        result: Any
        message: str
    state: ops.framework.StoredState
    ingress: IngressRequires
    _WP_CONFIG_PATH: str
    _CONTAINER_NAME: str
    _SERVICE_NAME: str
    _WORDPRESS_USER: str
    _WORDPRESS_GROUP: str
    _WORDPRESS_DB_CHARSET: str

    _DB_CHECK_INTERVAL: Union[float, int]
    _DB_CHECK_TIMEOUT: Union[float, int]

    _WORDPRESS_DEFAULT_THEMES: List[str]
    _WORDPRESS_DEFAULT_PLUGINS: List[str]
    def _on_start(self, _event: ops.charm.StartEvent) -> None: ...
    def _require_nginx_route(self) -> None: ...
    def _on_storage_attached(self, _event: ops.charm.StorageAttachedEvent) -> None: ...
    def _on_get_initial_password_action(self, event: ops.charm.ActionEvent) -> None: ...
    def _on_rotate_wordpress_secrets_action(self, event: ops.charm.ActionEvent) -> None: ...
    @staticmethod
    def _wordpress_secret_key_fields() -> List[str]: ...
    def _generate_wp_secret_keys(self) -> Dict[str, str]: ...
    def _replica_relation_data(self) -> ops.charm.model.RelationDataContent: ...
    def _replica_consensus_reached(self) -> bool: ...
    def _setup_replica_data(self, event: ops.charm.LeaderElectedEvent) -> None: ...
    def _on_relation_database_changed(
        self, event: opslib.mysql.MySQLDatabaseChangedEvent
    ) -> None: ...
    def _gen_wp_config(self) -> str: ...
    def _container(self) -> ops.charm.model.Container: ...
    def _wordpress_service_exists(self) -> bool: ...
    def _stop_server(self) -> None: ...
    def _run_cli(
        self,
        cmd: List[str],
        user: Optional[str] = None,
        group: Optional[str] = None,
        working_dir: Optional[str] = None,
        combine_stderr: bool = False,
        timeout: int = 60,
    ) -> CommandExecResult: ...
    def _run_wp_cli(
        self, cmd: List[str], timeout: Optional[int] = 60, combine_stderr: bool = False
    ) -> CommandExecResult: ...
    def _wrapped_run_wp_cli(
        self, cmd: List[str], timeout: Optional[int] = 60, error_message: Optional[str] = None
    ) -> ExecResult: ...
    def _wp_is_installed(self) -> None: ...
    def _current_effective_db_info(self) -> DatabaseConfig | None: ...
    def _test_database_connectivity(self) -> Tuple[bool, str]: ...
    def _wp_install_cmd(self) -> List[str]: ...
    def _wp_install(self) -> None: ...
    def _init_pebble_layer(self) -> None: ...
    def _start_server(self) -> None: ...
    def _current_wp_config(self) -> Optional[str]: ...
    def _remove_wp_config(self) -> None: ...
    def _push_wp_config(self, wp_config: str) -> None: ...
    def _check_addon_type(self, addon_type: str) -> None: ...
    def _wp_addon_list(self, addon_type: str) -> ExecResultListOfAddonInfoDict: ...
    def _wp_addon_install(self, addon_type: str, addon_name: str) -> ExecResult: ...
    def _wp_addon_uninstall(self, addon_type: str, addon_name: str) -> ExecResult: ...
    def _addon_reconciliation(self, addon_type: str) -> None: ...
    def _theme_reconciliation(self) -> None: ...
    def _wp_option_update(
        self, option: str, value: str, format_: str = "plaintext"
    ) -> ExecResult: ...
    def _wp_option_delete(self, option: str) -> ExecResult: ...
    def _wp_plugin_activate(self, plugin: str) -> ExecResult: ...
    def _wp_plugin_deactivate(self, plugin: str) -> ExecResult: ...
    def _perform_plugin_activate_or_deactivate(self, plugin: str, action: str) -> ExecResult: ...
    def _activate_plugin(
        self, plugin: str, options: Dict[str, Union[str, Dict[str, str]]]
    ) -> ExecResult: ...
    def _deactivate_plugin(self, plugin: str, options: List[str]) -> ExecResult: ...
    def _plugin_akismet_reconciliation(self) -> None: ...
    def _wp_eval(self, php_code: str) -> ExecResult: ...
    @staticmethod
    def _encode_openid_team_map(team_map: str) -> str: ...
    def _plugin_openid_reconciliation(self) -> None: ...
    def _apache_config_is_enabled(self, conf_name: str) -> bool: ...
    def _apache_enable_config(self, conf_name: str, conf: str) -> None: ...
    def _apache_disable_config(self, conf_name: str) -> None: ...
    def _swift_config(self) -> dict: ...
    def _config_swift_plugin(self, swift_config: dict) -> None: ...
    def _plugin_swift_reconciliation(self) -> None: ...
    def _plugin_reconciliation(self) -> None: ...
    def _core_reconciliation(self) -> None: ...
    def _storage_mounted(self) -> bool: ...
    def _reconciliation(self, _event: ops.charm.EventBase) -> None: ...
    def _on_apache_prometheus_exporter_pebble_ready(
        self, event: ops.charm.PebbleReadyEvent
    ) -> None: ...
