from typing import Optional, List, Dict

import ops
import ops.framework
import opslib.mysql


class WordpressCharm(ops.charm.CharmBase):
    state: ops.framework.StoredState

    @staticmethod
    def _wordpress_secret_key_fields() -> List[str]: ...

    def _generate_wp_secret_keys(self) -> Dict[str, str]: ...

    def _replica_relation_data(self) -> ops.charm.model.RelationDataContent: ...

    def _replica_consensus_reached(self) -> bool: ...

    def _on_leader_elected_replica_data_handler(self, event: ops.charm.LeaderElectedEvent): ...

    def _on_relation_database_changed(
            self,
            event: opslib.mysql.MySQLDatabaseChangedEvent
    ): ...

    def _gen_wp_config(self) -> str: ...

    def _container(self) -> ops.charm.model.Container: ...

    def _wordpress_service_exists(self) -> bool: ...

    def _stop_server(self): ...

    def _wp_is_installed(self): ...

    def _wp_install_cmd(self) -> List[str]: ...

    def _wp_install(self): ...

    def _init_pebble_layer(self): ...

    def _start_server(self): ...

    @staticmethod
    def _wp_config_path() -> str: ...

    def _current_wp_config(self) -> Optional[str]: ...

    def _push_wp_config(self, wp_config: str): ...

    def _core_reconciliation(self): ...

    def _reconciliation(self, _event: ops.charm.EventBase): ...