name: build-cache.yaml
on:
  pull_request:
jobs:
  build-rock:
    name: Build Rock without Cache
    runs-on: ubuntu-latest
    steps:
      - uses: canonical/setup-lxd@v0.1.3
      - uses: actions/checkout@v5.0.0
      - uses: canonical/operator-workflows/internal/build@main
        id: build
        with:
          build-plan: |
            {
              "type": "rock",
              "name": "wordpress",
              "source_file": "wordpress_rock/rockcraft.yaml",
              "source_directory": "wordpress_rock",
              "output_type": "registry",
              "output": "${{ github.run_id }}_${{ github.run_attempt }}__build__output__rock__wordpress"
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
  build-rock-cache:
    name: Build Rock with Cache
    runs-on: ubuntu-latest
    steps:
      - uses: canonical/setup-lxd@v0.1.3
      - uses: actions/checkout@v5.0.0
      - uses: canonical/operator-workflows/internal/build@cache
        id: build
        with:
          build-plan: |
            {
              "type": "rock",
              "name": "wordpress",
              "source_file": "wordpress_rock/rockcraft.yaml",
              "source_directory": "wordpress_rock",
              "output_type": "registry",
              "output": "${{ github.run_id }}_${{ github.run_attempt }}__build__output__rock__wordpress_cached"
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
  build-charm-cache:
    name: Build Charm with Cache
    runs-on: ubuntu-latest
    steps:
      - uses: canonical/setup-lxd@v0.1.3
      - uses: actions/checkout@v5.0.0
      - uses: canonical/operator-workflows/internal/build@cache
        id: build
        with:
          build-plan: |
            {
              "type": "charm",
              "name": "wordpress-k8s",
              "source_file": "charmcraft.yaml",
              "source_directory": ".",
              "output_type": "file",
              "output": "${{ github.run_id }}_${{ github.run_attempt }}__build__output__charm__wordpress-k8s_cached"
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
