name: integration-tests-juju3

on:
  pull_request:
  workflow_call:

jobs:
  integration-test-juju3:
    name: Integration Test on Juju3
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      extra-arguments: >-
        --openstack-rc=${GITHUB_WORKSPACE}/openrc
        --kube-config=${GITHUB_WORKSPACE}/kube-config
        --screenshot-dir=/tmp
      juju-channel: 3/stable
      channel: 1.29-strict/stable
      modules: '["test_addon", "test_core", "test_cos_grafana", "test_cos_loki", "test_cos_prometheus"]'
      pre-run-script: |
        -c "sudo microk8s enable hostpath-storage
          sudo microk8s kubectl -n kube-system rollout status -w deployment/hostpath-provisioner
          sudo microk8s config > ${GITHUB_WORKSPACE}/kube-config
          chmod +x tests/integration/pre_run_script_juju3.sh
          ./tests/integration/pre_run_script_juju3.sh"
      test-tox-env: "integration-juju3"
      setup-devstack-swift: true
      trivy-image-config: ./trivy.yaml
      tmate-debug: true
