# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

name: Publish Tutorial Notebook

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-release:
    name: Publish Notebook to Release
    permissions:
      contents: write
    uses: canonical/canonical-sphinx-notebooks/.github/workflows/publish-notebooks.yaml@48c6e2fcf0bf44fc0cc1af230c26f055538d2aa1
    with:
      execute-workflow-file: execute_tutorial_notebook.yaml
      artifact-name: tutorial-notebook
      release-tag: docs-latest
      asset-name: tutorial.ipynb
